import { useState, useEffect, useRef } from "react";
import { CampaignPageShell } from "@product/components/campaign/CampaignPageShell";
import { Button } from "@product/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@product/components/ui/card";
import { Badge } from "@product/components/ui/badge";
import { ScrollArea } from "@product/components/ui/scroll-area";
import { ICPForm } from "@product/components/icp/ICPForm";
import { NextStepBanner } from "@product/components/campaign/NextStepBanner";
import {
  AutoGenerateDocument,
  AutoGenerateDocumentRef,
} from "@product/components/icp/AutoGenerateDocument";
import {
  Target,
  Users,
  Loader2,
  Pencil,
  RefreshCw,
  Building2,
  Globe,
  MessageSquare,
  Palette,
  AlertTriangle,
  Zap,
  Download,
  Package,
} from "lucide-react";
import {
  fetchICPByCampaign,
  generateICPDocument,
  getICPDownloadUrl,
  ICPProfile,
  ICPData,
} from "@product/lib/api";
import { getToken } from "@product/lib/api-client";
import { useToast } from "@product/hooks/use-toast";
import { useCampaignStore } from "@product/store/campaignStore";

const DEFAULT_ICP_DATA: ICPData = {
  industry: null,
  companySize: null,
  roles: [],
  painPoints: [],
  buyingTriggers: [],
  regions: [],
  messagingAngles: [],
  solution: null,
  contentTone: null,
  additionalNotes: "",
};

function ICPPreview({
  icp,
  onEdit,
  onRegenerate,
  onDownload,
  isRegenerating,
}: {
  icp: ICPProfile;
  onEdit: () => void;
  onRegenerate: () => void;
  onDownload: () => void;
  isRegenerating: boolean;
}) {
  const d = icp.data;
  return (
    <div className="mx-auto w-full max-w-[1180px] space-y-6 px-8 py-8">
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div className="min-w-0">
          <p className="mb-1.5 text-[11px] font-semibold uppercase tracking-[0.13em] text-primary">
            Ideal customer profile
          </p>
          <h2 className="truncate font-display text-[26px] font-bold tracking-[-0.02em] text-foreground">
            {icp.name}
          </h2>
          <p className="mt-1 text-[14px] text-muted-foreground">
            Updated {new Date(icp.updatedAt).toLocaleDateString()}
          </p>
        </div>
        <div className="flex gap-2">
          {icp.generatedFilePath && (
            <Button
              variant="outline"
              size="sm"
              onClick={onDownload}
              className="gap-2"
            >
              <Download className="w-4 h-4" /> Download ICP
            </Button>
          )}
          <Button
            variant="outline"
            size="sm"
            onClick={onEdit}
            className="gap-2"
          >
            <Pencil className="w-4 h-4" /> Edit
          </Button>
          <Button
            variant="outline"
            size="sm"
            onClick={onRegenerate}
            disabled={isRegenerating}
            className="gap-2"
          >
            {isRegenerating ? (
              <Loader2 className="w-4 h-4 animate-spin" />
            ) : (
              <RefreshCw className="w-4 h-4" />
            )}
            {icp?.generatedFilePath !== null
              ? " Regenerate"
              : "Generate ICP Document"}
          </Button>
        </div>
      </div>

      <NextStepBanner campaignId={icp.campaignId} />

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {d.industry && (
          <Card>
            <CardHeader className="pb-2">
              <CardTitle className="flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[0.12em] text-muted-foreground">
                <Building2 className="h-3.5 w-3.5 text-primary" /> Industry
              </CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-[14.5px] leading-relaxed text-foreground">{d.industry}</p>
            </CardContent>
          </Card>
        )}
        {d.companySize && (
          <Card>
            <CardHeader className="pb-2">
              <CardTitle className="flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[0.12em] text-muted-foreground">
                <Users className="h-3.5 w-3.5 text-primary" /> Company Size
              </CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-[14.5px] leading-relaxed text-foreground">{d.companySize}</p>
            </CardContent>
          </Card>
        )}
      </div>

      {d.solution && (
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[0.12em] text-muted-foreground">
              <Package className="w-4 h-4 text-primary" /> Solution / Product
              Being Sold
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-[14.5px] leading-relaxed text-foreground">{d.solution}</p>
          </CardContent>
        </Card>
      )}

      {d.roles.length > 0 && (
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[0.12em] text-muted-foreground">
              <Target className="w-4 h-4 text-primary" /> Target Roles
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex flex-wrap gap-2">
              {d.roles.map((r) => (
                <Badge key={r} variant="secondary">
                  {r}
                </Badge>
              ))}
            </div>
          </CardContent>
        </Card>
      )}

      {d.painPoints.length > 0 && (
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[0.12em] text-muted-foreground">
              <AlertTriangle className="w-4 h-4 text-primary" /> Pain Points
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex flex-wrap gap-2">
              {d.painPoints.map((p) => (
                <Badge key={p} variant="outline">
                  {p}
                </Badge>
              ))}
            </div>
          </CardContent>
        </Card>
      )}

      {d.buyingTriggers.length > 0 && (
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[0.12em] text-muted-foreground">
              <Zap className="w-4 h-4 text-primary" /> Buying Triggers
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex flex-wrap gap-2">
              {d.buyingTriggers.map((t) => (
                <Badge key={t} variant="outline">
                  {t}
                </Badge>
              ))}
            </div>
          </CardContent>
        </Card>
      )}

      {d.regions.length > 0 && (
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[0.12em] text-muted-foreground">
              <Globe className="w-4 h-4 text-primary" /> Target Regions
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex flex-wrap gap-2">
              {d.regions.map((r) => (
                <Badge key={r} variant="secondary">
                  {r}
                </Badge>
              ))}
            </div>
          </CardContent>
        </Card>
      )}

      {d.messagingAngles.length > 0 && (
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[0.12em] text-muted-foreground">
              <MessageSquare className="w-4 h-4 text-primary" /> Messaging
              Angles
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex flex-wrap gap-2">
              {d.messagingAngles.map((a) => (
                <Badge key={a} variant="outline">
                  {a}
                </Badge>
              ))}
            </div>
          </CardContent>
        </Card>
      )}

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {d.contentTone && (
          <Card>
            <CardHeader className="pb-2">
              <CardTitle className="flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[0.12em] text-muted-foreground">
                <Palette className="w-4 h-4 text-primary" /> Content Tone
              </CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-[14.5px] capitalize leading-relaxed text-foreground">
                {d.contentTone}
              </p>
            </CardContent>
          </Card>
        )}
        {d.additionalNotes && (
          <Card>
            <CardHeader className="pb-2">
              <CardTitle className="text-[11px] font-semibold uppercase tracking-[0.12em] text-muted-foreground">Additional Notes</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-[14.5px] leading-relaxed text-muted-foreground">
                {d.additionalNotes}
              </p>
            </CardContent>
          </Card>
        )}

      </div>
    </div>
  );
}

function ICPInner({
  campaignId,
  campaignName,
}: {
  campaignId: string;
  campaignName: string | null;
}) {
  const { toast } = useToast();
  const [icp, setIcp] = useState<ICPProfile | null>(null);
  const [icpLoading, setIcpLoading] = useState(true);
  /** Distinct from "this campaign has no ICP". See loadICP. */
  const [icpLoadError, setIcpLoadError] = useState<string | null>(null);
  const [editMode, setEditMode] = useState(false);
  const [isRegenerating, setIsRegenerating] = useState(false);
  const [currentFormData, setCurrentFormData] =
    useState<ICPData>(DEFAULT_ICP_DATA);
  const autoGenerateRef = useRef<AutoGenerateDocumentRef>(null);

  useEffect(() => {
    loadICP();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [campaignId]);

  const loadICP = async () => {
    setIcpLoading(true);
    setIcpLoadError(null);
    try {
      const data = await fetchICPByCampaign(campaignId);
      setIcp(data);
      setCurrentFormData(data.data);
    } catch (err: any) {
      /*
        A 404 genuinely means "no ICP yet". Anything else does not.

        Every failure used to be flattened into null, so a session timeout or a
        server hiccup silently moved someone from "here is your ICP" into an
        empty editing form — the same failure mode the form component next door
        already guards against, with a comment explaining why.
      */
      setIcp(null);
      if (err?.status !== 404) {
        setIcpLoadError(err?.message || "Couldn't load this ICP. Your saved answers are safe.");
      }
    } finally {
      setIcpLoading(false);
    }
  };

  const handleSaveComplete = () => {
    loadICP();
    setEditMode(false);
  };

  const handleDownloadICP = async () => {
    try {
      const url = getICPDownloadUrl(campaignId);
      const token = getToken();
      const res = await fetch(url, {
        headers: token ? { Authorization: `Bearer ${token}` } : {},
      });
      /*
        Three different failures used to read identically, so an expired session
        sent people looking for a broken file instead of signing back in.
      */
      if (!res.ok) {
        throw new Error(
          res.status === 401
            ? "Your session has expired. Sign in again."
            : res.status === 404
              ? "There is no document yet. Generate one first."
              : "The document could not be prepared. Try again in a moment."
        );
      }
      const blob = await res.blob();
      const a = document.createElement("a");
      a.href = URL.createObjectURL(blob);
      a.download = `icp-report-${campaignId}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(a.href);
    } catch (err: any) {
      toast({
        title: "Couldn't download the document",
        description: err?.message || "Something went wrong. Try again in a moment.",
        variant: "destructive",
      });
    }
  };

  const handleRegenerate = async () => {
    setIsRegenerating(true);
    try {
      await generateICPDocument(campaignId);
      toast({
        title: "Regenerated",
        description: "ICP document has been regenerated.",
      });
      await loadICP();
    } catch (err: any) {
      /*
        Show the server's reason, not a restatement of the verb.

        The server explains exactly what is missing — "Your ICP needs what you
        sell before a document can be generated" — and this caught the error
        without binding it, replacing a sentence that names the fix with
        "Failed to regenerate", which names nothing. Someone reading that has
        no way to know a single empty field is the cause.
      */
      toast({
        title: "Couldn't regenerate",
        description: err?.message || "Something went wrong. Try again in a moment.",
        variant: "destructive",
      });
    } finally {
      setIsRegenerating(false);
    }
  };

  const showICPForm = !icp || editMode;

  if (icpLoading) {
    return (
      <div className="flex items-center justify-center h-full">
        <Loader2 className="w-8 h-8 animate-spin text-primary" />
      </div>
    );
  }

  /*
    A failed load must not open a blank form.

    Dropping straight into the editor after an error looks exactly like "you
    have no ICP", and the obvious next action — filling it in and saving — can
    create a second profile alongside the one that failed to load.
  */
  if (icpLoadError && !icp) {
    return (
      <div className="flex h-full flex-col items-center justify-center gap-4 px-6 text-center">
        <AlertTriangle className="h-8 w-8 text-muted-foreground" />
        <div className="space-y-1.5">
          <p className="font-display text-[17px] font-semibold text-foreground">
            Couldn't load this ICP
          </p>
          <p className="max-w-[42ch] text-[14px] leading-relaxed text-muted-foreground">
            {icpLoadError} Nothing has been changed.
          </p>
        </div>
        <Button variant="outline" onClick={loadICP} className="gap-2">
          <RefreshCw className="h-4 w-4" /> Try again
        </Button>
      </div>
    );
  }

  /*
    Does the form on screen still match what the server holds?

    The Generate button decided whether to enable itself from the LIVE form,
    but the request sends only a campaign id and the server rebuilds the prompt
    from the SAVED row. So editing an ICP and generating without saving paid for
    a document describing the old answers and reported it as a success — and
    filling in a brand-new ICP without saving produced "no ICP exists".
  */
  const savedSnapshot = JSON.stringify(icp?.data ?? null);
  const liveSnapshot = JSON.stringify(currentFormData ?? null);
  const hasUnsavedChanges = !!icp && savedSnapshot !== liveSnapshot;

  if (showICPForm) {
    return (
      <div className="flex flex-1 overflow-hidden h-full">
        <div className="flex-1 bg-background overflow-y-auto">
          <ICPForm
            campaignId={campaignId}
            onSave={() => {}}
            onDataChange={(data) => setCurrentFormData(data)}
            onSaveComplete={handleSaveComplete}
          />
        </div>
        <div className="w-[400px] border-l border-border bg-card/30 p-4 overflow-y-auto">
          <AutoGenerateDocument
            ref={autoGenerateRef}
            icpData={currentFormData}
            icpName={campaignName || undefined}
            campaignId={campaignId}
            generatedFilePath={icp?.generatedFilePath ?? null}
            savedDocument={icp?.generatedDocument ?? null}
            hasUnsavedChanges={hasUnsavedChanges}
          />
        </div>
      </div>
    );
  }

  return (
    <ScrollArea className="h-full">
      <ICPPreview
        icp={icp!}
        onEdit={() => setEditMode(true)}
        onRegenerate={handleRegenerate}
        onDownload={handleDownloadICP}
        isRegenerating={isRegenerating}
      />
    </ScrollArea>
  );
}

export default function ICPPage() {
  const activeCampaignName = useCampaignStore((s) => s.activeCampaignName);
  return (
    <CampaignPageShell>
      {(campaignId) => (
        <div className="flex-1 overflow-hidden">
          <ICPInner
            key={campaignId}
            campaignId={campaignId}
            campaignName={activeCampaignName}
          />
        </div>
      )}
    </CampaignPageShell>
  );
}
