/**
 * The article body.
 *
 * This is the ONLY `dangerouslySetInnerHTML` in the blog, and the only place
 * that is allowed to be. `body` reaches here exclusively from
 * `renderPostHtml()` in lib/blog/html.js, which is where sanitisation happens.
 * Concentrating it in one component means reviewing the safety of the whole
 * blog is reviewing one file.
 *
 * The typography lives in `.vf-prose` in globals.css rather than on this
 * element, because the markup inside is generated by an editor and cannot carry
 * classes of its own — descendant selectors are the only way to reach it.
 */
export default function ArticleBody({ body }) {
  return (
    <div
      className="vf-prose"
      // eslint-disable-next-line react/no-danger -- sanitized in lib/blog/html.js
      dangerouslySetInnerHTML={{ __html: body }}
    />
  );
}
