import { useState, useImperativeHandle, forwardRef } from "react";
import { Button } from "@product/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@product/components/ui/card";
import { ScrollArea } from "@product/components/ui/scroll-area";
import { Separator } from "@product/components/ui/separator";
import { 
  FileText, Sparkles, Copy, Check, Download, Loader2, CheckCircle2
} from "lucide-react";
import { ICPData, generateICPDocument } from "@product/lib/api";
import { useToast } from "@product/hooks/use-toast";

interface AutoGenerateDocumentProps {
  icpData: ICPData;
  icpName?: string;
  campaignId?: string;
  generatedFilePath?: string | null;
  /** The stored document, so a reload does not lose it. */
  savedDocument?: string | null;
  /** True when the form has edits the server has not seen. */
  hasUnsavedChanges?: boolean;
}

export interface AutoGenerateDocumentRef {
  triggerGenerate: () => void;
}

type WorkflowStep = "idle" | "generating" | "success" | "error";

export const AutoGenerateDocument = forwardRef<AutoGenerateDocumentRef, AutoGenerateDocumentProps>(
  ({ icpData, icpName, campaignId, generatedFilePath, savedDocument, hasUnsavedChanges }, ref) => {
  /*
    Seeded from what the server stored, not from nothing.

    The document was held here in component state alone, so a page reload
    dropped it and the preview screen went back to showing the ten input fields
    and none of the output — a customer who refreshed reasonably concluded that
    generation had not worked.
  */
  const [generatedDocument, setGeneratedDocument] = useState<string | null>(savedDocument ?? null);
  const [workflowStep, setWorkflowStep] = useState<WorkflowStep>(savedDocument ? "success" : "idle");
  const [filePath, setFilePath] = useState<string | null>(null);
  const [errorMessage, setErrorMessage] = useState<string>("");
  const [copied, setCopied] = useState(false);
  const { toast } = useToast();

  const canGenerate = icpData.industry && icpData.companySize && icpData.roles.length > 0;

  useImperativeHandle(ref, () => ({
    triggerGenerate: () => {
      if (canGenerate && campaignId) {
        executeGenerate();
      }
    }
  }));

  const executeGenerate = async () => {
    if (!canGenerate || !campaignId) {
      toast({
        title: "Incomplete ICP",
        description: "Please fill in industry, company size, and at least one role.",
        variant: "destructive"
      });
      return;
    }

    /*
      The server builds the document from the saved row, not from the form on
      screen. Generating with unsaved edits therefore pays for a document about
      the previous answers and presents it as a success.
    */
    if (hasUnsavedChanges) {
      toast({
        title: "Save your changes first",
        description: "The document is built from your saved ICP, so unsaved edits would not be included.",
        variant: "destructive"
      });
      return;
    }

    setErrorMessage("");
    setWorkflowStep("generating");

    try {
      const result = await generateICPDocument(campaignId);
      setGeneratedDocument(result.content);
      setFilePath(result.filePath);
      setWorkflowStep("success");

      toast({
        title: "Document Generated & Saved",
        description: "ICP document has been saved to the campaign folder."
      });
    } catch (err) {
      const message = err instanceof Error ? err.message : "Failed to generate document";
      setErrorMessage(message);
      setWorkflowStep("error");
    }
  };

  const handleCopy = async () => {
    if (!generatedDocument) return;
    await navigator.clipboard.writeText(generatedDocument);
    setCopied(true);
    toast({ title: "Copied", description: "Document copied to clipboard." });
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    if (!generatedDocument) return;
    const blob = new Blob([generatedDocument], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `icp-report.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast({ title: "Downloaded", description: "Document saved locally." });
  };

  const resetWorkflow = () => {
    setWorkflowStep("idle");
    setErrorMessage("");
  };

  return (
    <Card className="h-full flex flex-col">
      <CardHeader className="pb-3 flex-shrink-0">
        <div className="flex items-center justify-between">
          <CardTitle className="flex items-center gap-2 text-base">
            <FileText className="w-4 h-4 text-primary" />
            Auto-Generate ICP Document
          </CardTitle>
          {generatedDocument && (
            <div className="flex gap-1">
              <Button variant="ghost" size="icon" onClick={handleCopy} className="h-8 w-8">
                {copied ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
              </Button>
              <Button variant="ghost" size="icon" onClick={handleDownload} className="h-8 w-8">
                <Download className="w-3 h-3" />
              </Button>
            </div>
          )}
        </div>
      </CardHeader>
      <Separator />
      <CardContent className="flex-1 pt-4 overflow-hidden flex flex-col">
        
        {/* Idle State */}
        {workflowStep === "idle" && !generatedDocument && (
          <div className="flex-1 flex flex-col items-center justify-center text-center space-y-4">
            <div className="w-16 h-16 rounded-2xl bg-primary/10 flex items-center justify-center">
              <Sparkles className="w-8 h-8 text-primary" />
            </div>
            <div className="space-y-2">
              <h3 className="font-semibold text-foreground">
                {generatedFilePath ? "Regenerate & Save" : "Generate & Save"}
              </h3>
              <p className="text-sm text-muted-foreground max-w-sm">
                {!canGenerate
                  ? "Fill in industry, company size, and at least one role to enable generation."
                  : hasUnsavedChanges
                    ? "Save your ICP first — the document is built from your saved answers, not the form on screen."
                    : "Generate an AI-powered ICP document using your saved ICP profile."}
              </p>
            </div>
            {/* Disabled while unsaved, so the reason is visible before the
                click rather than only in a toast afterwards. */}
            <Button
              onClick={executeGenerate}
              disabled={!canGenerate || !campaignId || hasUnsavedChanges}
              className="gap-2"
            >
              <Sparkles className="w-4 h-4" />
              {generatedFilePath ? "Regenerate ICP Document" : "Generate ICP Document"}
            </Button>
          </div>
        )}

        {/* Generating */}
        {workflowStep === "generating" && (
          <div className="flex-1 flex flex-col items-center justify-center text-center space-y-4">
            <div className="w-16 h-16 rounded-2xl bg-primary/10 flex items-center justify-center">
              <Loader2 className="w-8 h-8 text-primary animate-spin" />
            </div>
            {/* A bare spinner with no sense of time meant people could not tell
                "working" from "hung", so they reloaded or clicked again — which,
                on a previously uncapped endpoint, meant a second paid call. */}
            <h3 className="font-semibold text-foreground">Writing your ICP document</h3>
            <p className="text-sm text-muted-foreground">
              This usually takes 20&ndash;40 seconds. Leaving this page cancels nothing.
            </p>
          </div>
        )}

        {/* Success */}
        {workflowStep === "success" && generatedDocument && (
          <div className="flex-1 flex flex-col overflow-hidden">
            <div className="mb-3 flex items-center gap-2 rounded-xl border border-success/20 bg-success/[0.08] p-3">
              <CheckCircle2 className="h-5 w-5 flex-shrink-0 text-success" />
              <div className="flex-1 min-w-0">
                <p className="text-sm font-medium text-foreground">Document Saved</p>
                {filePath && <p className="text-xs text-muted-foreground truncate">{filePath}</p>}
              </div>
            </div>
            
            <div className="flex items-center justify-between mb-2">
              <span className="text-sm text-muted-foreground">Generated Document</span>
              <Button variant="ghost" size="sm" onClick={executeGenerate} className="gap-1 text-xs">
                <Sparkles className="w-3 h-3" />
                Regenerate
              </Button>
            </div>
            
            <ScrollArea className="flex-1 rounded-md border bg-muted/30 p-4">
              <div className="prose prose-sm dark:prose-invert max-w-none whitespace-pre-wrap font-mono text-xs">
                {generatedDocument}
              </div>
            </ScrollArea>
          </div>
        )}

        {/* Error */}
        {workflowStep === "error" && (
          <div className="flex-1 flex flex-col items-center justify-center text-center space-y-4">
            <p className="text-sm text-destructive">{errorMessage}</p>
            <Button onClick={resetWorkflow}>Try again</Button>
          </div>
        )}
      </CardContent>
    </Card>
  );
});

AutoGenerateDocument.displayName = "AutoGenerateDocument";
